config/routes.rb
Rails.application.routes.draw do
  get 'site/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'site#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Overtheditch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'vendor' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar navbar-expand-lg fixed-top">
      <%= link_to "Overtheditch", site_index_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="nav-collapse">
        <ul class="navbar-nav ml-auto ">
          <li class="nav-item">
            <%= link_to "Learn", "#Learn", class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "About", "#about" , class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "FAQ", "#tokens", class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Check Eligibility", '#whitepaper', class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "More", '#roadmap' , class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/site/index.html.erb
<div id="fullpage">

  <div class="section" id="home">
    <div class="container">
      <h1 class="col-offset-3 col-6-md">Transfer your Kiwisaver to any Australian Super account</h1>
      <div class="text-center">
        <button type="button" class="cta btn btn-lg btn-success">Am I eligible?</button>
      </div>
    </div>
  </div>

  <div class="section" id="learn">
    <div class="container">
      <h1 class="col-offset-3 col-6-md">The Kiwisaver process</h1>
      <div class="row">
        <div class="col-4">
          <i class="fas fa-circle" style="font-size: 150pt"></i>
        </div>
        <div class="col-6">
          <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">
              <h4>How it works</h4>
              <h2 class="info-subheading">Check Eligibility</h2>
              <p class="info-text">Begin the process by clicking here and filling out our simple eligibility form. You will need to tell us your current Kiwissaver provider as well as your nominated Australian Super Fund.</p>
            </div>
            <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">
              <h4>Get in touch now</h4>
              <h2 class="info-subheading">Contact is made</h2>
              <p class="info-text">Begin the process by clicking here and filling out our simple eligibility form. You will need to tell us your current Kiwissaver provider as well as your nominated Australian Super Fund.</p>
            </div>
            <div class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">...</div>
          </div>
        </div>
        <div class="col-2">
          <div class="list-group process-list-group" id="list-tab" role="tablist">
            <a class="process-button active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Check Eligibility <i class="fas fa-circle"></i></a>

            <a class="process-button" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">Contact <i class="fas fa-circle"></i></a>
            <a class="process-button" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">Kiwisaver transferred <i class="fas fa-circle"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="section" id="about" >Section 3</div>
  <div class="section" id="faq">Section 4</div>
  <div class="section" id="check">Section 4</div>
  <div class="section" id="more">Section 4</div>
</div>